.travis.yml

macOS builds are not ready, remove from daily

---

src/server_manager/install_scripts/install_server.sh

This tweaks the firewall message to make it clearer where the problem might be.
Also, I forgot to add the `curl` comment to https://github.com/Jigsaw-Code/outline-server/pull/38

Tweak message

---

src/server_manager/install_scripts/install_server.sh

Still output ports on firewall blocked

---

src/server_manager/install_scripts/install_server.sh

Allow specifying non-IPv4 (domain name, IPv6) server addresses

---

src/server_manager/electron_app/loading.html
src/server_manager/ui_components/app-root.html
src/server_manager/ui_components/outline-tos-view.html

* Prompts the user to accept the ToS before using the app.
* Re-styles the loading page for visual consistency.

Display a Terms of Service screen on startup

---

release/release_data.json
src/metrics_server/README.md
src/metrics_server/deploy_prod_action.sh
src/metrics_server/deploy_test_action.sh
src/metrics_server/post_server_report.ts
src/server_manager/electron_app/digital_ocean_modifications.ts
src/server_manager/model/server.ts
src/server_manager/ui_components/outline-intro-step.html
src/server_manager/ui_components/outline-server-view.html
src/server_manager/web_app/app.spec.ts
src/server_manager/web_app/app.ts
src/server_manager/web_app/digitalocean_server.ts
src/shadowbox/model/shadowsocks_server.ts
src/shadowbox/server/libev_shadowsocks_server.ts
src/shadowbox/server/managed_user.ts
src/shadowbox/server/mocks/mocks.ts

This also clarifies the semantics in the code.
Fixes the part of #121 that is in the Manager and Server.

Fix DO transfer limit

---

src/server_manager/web_app/app.ts

Mitigates errors in terminals that truncate the server installation script output.

Remove whitespace from server config input

---

src/server_manager/electron_app/index.ts

Implements logic to support a single application window.

Disallow multiple application windows

---

src/server_manager/model/server.ts
src/server_manager/ui_components/outline-iconset.html
src/server_manager/ui_components/outline-server-settings.html
src/server_manager/ui_components/outline-server-view.html
src/server_manager/web_app/app.spec.ts
src/server_manager/web_app/app.ts
src/server_manager/web_app/shadowbox_server.ts

* Moves server deletion to the main screen:
* Exposes the server hostname, management port, and creation date in the server details section:

Re-style server settings UI

---

src/server_manager/package.json

Just a version number bump; merging TBR.

prepare for server manager 1.1.2 release

---

src/shadowbox/docker/Dockerfile

https://github.com/Jigsaw-Code/outline-server/issues/114

shadowbox node and shadowsocks-libev upgrades

---

src/server_manager/package.json

bump version number for server manager release

---

src/server_manager/electron_app/digitalocean_oauth.ts
src/server_manager/electron_app/index.ts
src/server_manager/electron_app/preload.ts
src/server_manager/types/preload.d.ts
src/server_manager/web_app/app.spec.ts
src/server_manager/web_app/app.ts
src/server_manager/web_app/digitalocean_server.ts
src/server_manager/web_app/manual_server.ts
src/server_manager/web_app/shadowbox_server.ts

Nothing urgent but when I got looking at `preload.ts` it really bugged me. I've followed Signal's general approach, adding some type safety:
https://github.com/signalapp/Signal-Desktop/blob/development/preload.js
Overall, I think it's an improvement.

refactor preload.ts, remove some unnecessary events

---

src/server_manager/install_scripts/install_server.sh

At some point this stopped working. Since it's due to escaping and escaping is hard, I made it use less escaping.

fix firewall warning output

---

src/shadowbox/README.md

Minor fix. The current command breaks the prompts.

Fix install command documentation

---

src/shadowbox/package.json
yarn.lock

Guess we forgot to do this. This matches the client.

migrate to latest shadowsocksconfig

---

src/shadowbox/server/main.ts

I would like to merge and release this later today.

enable prometheus-based metrics on 10% of servers

---

src/shadowbox/server/main.ts

I intend to release this on Thursday, and full rollout next week if things go well.

Rollout outline-ss-server to 10%

---

scripts/do_action.sh
src/metrics_server/build.sh
src/metrics_server/deploy_prod_action.sh
src/metrics_server/deploy_test_action.sh
src/metrics_server/test_action.sh
src/server_manager/electron_app/build_action.sh
src/server_manager/electron_app/package_linux_action.sh
src/server_manager/electron_app/package_macos_action.sh
src/server_manager/electron_app/package_only_windows_action.sh
src/server_manager/electron_app/release_linux_action.sh
src/server_manager/electron_app/release_macos_action.sh
src/server_manager/electron_app/release_windows_action.sh
src/server_manager/electron_app/run_action.sh
src/server_manager/install_scripts/do_install_server.sh
src/server_manager/web_app/build_action.sh
src/shadowbox/docker/build_action.sh
src/shadowbox/server/build_action.sh

Minor cleanup:
- Removed line printing
- Added action indentation
- Added error indication
Example:
@trevj FYI

Clean up build output

---

src/shadowbox/integration_test/test.sh
src/shadowbox/server/main.ts

Also removes the color filter, since outline-ss-server doesn't output color anymore, unless it's the terminal

Rollout to 30%

---

src/shadowbox/README.md

Updating documentation given user feedback, clarifying where to obtain the appropriate parameters to issue an API call to the server. This also simplifies construction of the URL and allows for calling the server without needing to be SSH'd in in the first place.

Documentation update

---

src/shadowbox/server/main.ts

increase go server rollout to 50%

---

src/shadowbox/server/main.ts

Looking at the time now, I would probably roll this out Monday morning.

enable Go server globally

---

src/server_manager/web_app/app.spec.ts
src/server_manager/web_app/app.ts
src/server_manager/web_app/display_server.ts

This is still far from the coverage that we want, but it matches and extends the previous unit tests.

Re-implement broken tests, write tests for new functionality

---

src/server_manager/ui_components/outline-manual-server-entry.html

* Hides the underline in the manual server input textarea.
* Defines a mixin to reduce style duplication.

Manual server entry UI improvements

---

.travis.yml

Oops, forgot about this in https://github.com/Jigsaw-Code/outline-server/pull/349.

add sentry webhook function to travis

---

.travis.yml
src/server_manager/electron_app/build_action.sh
yarn.lock

move to latest node and yarn

---

src/shadowbox/docker/Dockerfile
src/shadowbox/infrastructure/get_port.spec.ts
src/shadowbox/infrastructure/get_port.ts

remove lsof from image, and unused code

---

src/server_manager/package.json
yarn.lock

https://github.com/electron-userland/electron-builder/releases/tag/v20.34.0 is the last that supports Electron 2.x:
https://github.com/electron-userland/electron-builder/issues/3505#issuecomment-442156509

update electron to 2.0.16, electron-builder 20.34.0

---

src/sentry_webhook/post_sentry_event_to_salesforce.ts

Sends the URL for the Sentry event to Salesforce, instead of the raw event ID.

Post Sentry URL instead of event ID to Salesforce

---

src/shadowbox/server/main.ts

enable single port at 100%

---

src/server_manager/install_scripts/install_server.sh
src/shadowbox/server/main.ts

- Update the firewall instruction on the install script
- Fix potential config writing issue that could cause the portForNewAccessKeys to change
- Remove rollout

Single port cleanup

---

src/server_manager/package.json
src/server_manager/ui_components/outline-server-view.html
yarn.lock

Just something I noticed while working on other stuff.

update to latest bytes, remove KB hack (now fixed)

---

src/server_manager/ui_components/outline-server-settings.html

I forgot to push the fix last time.

Remove the extra space.

---

src/server_manager/ui_components/outline-server-settings.html

Very small PR to correct a typo in the server settings template for the word 'monthly'

Corrected a typo on 'monthly'

---

src/server_manager/index.html

There are still many things to fix, but this is a first step.
Demo: https://outline-manager.viniciusfortuna.com/

Make web app load on web

---

src/shadowbox/server/manager_service.ts

Changed magic number http codes to named enum values
De-nested control flow in setShareMetrics()
Formatted.

manager_service cleanup

---

src/server_manager/ui_components/outline-server-settings.html
src/server_manager/ui_components/outline-server-view.html
src/server_manager/web_app/app.ts

tested by running a local shadowbox server from the daily-2019-07-30 image on quay.io.

Disable editing key port for old servers

---

package.json
yarn.lock

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html for more information.  Among the nice new features are optional chainging and null coalescing, and assertion functions, as well as some additional safety checks in the compiler

Update to Typescript 3.7

---

src/shadowbox/server/manager_service.ts

* Properly stringifies the log response for listAccessKeys
* Fills in missing logging of nonempty responses

Update Manager Service Logging

---

src/server_manager/web_app/app.ts

Update data limits availability date

---

src/server_manager/ui_components/outline-server-settings.html

Directs the user to a data limits survey Google form
FYI, @cjhenck

Add data limits feedback survey link

---

src/server_manager/index.html
src/server_manager/ui_components/app-root.html
src/server_manager/ui_components/style.css
tsconfig.json

This is part of a series of PRs to make our dependencies more sane and move towards a better build and Typescript everywhere.

Simplify index.html

---

src/server_manager/package.json

Planning to release Outline Manager v1.5.0 tomorrow, April 28th.

Increase Outline Manager version

---

src/server_manager/package.json
src/server_manager/web_app/app.ts
yarn.lock

Fix sentry

---

.travis.yml
package.json
src/server_manager/base.webpack.js
src/server_manager/gallery.webpack.js
src/server_manager/package.json
src/server_manager/web_app/browser_main.ts
src/server_manager/web_app/gallery_app/index.html
src/server_manager/web_app/gallery_app/main.ts
src/server_manager/web_app/run_gallery_action.sh
tsconfig.json
tslint.json
yarn.lock

This will let us develop the UI components in isolation. Example:
You can quickly tweak the input and see if it's behaving correctly. This is also an example of using [LitElement](https://lit-element.polymer-project.org/) in our code.
cc: @JonathanDCohen @mpmcroy

Create Gallery App

---

src/shadowbox/docker/Dockerfile
src/shadowbox/package.json

This contains the geo ip improvement for UDP from @bemasc.

Release version 1.2.1

---

.travis.yml

* Fixes CI deployment on macOS.

Travis: install docker 19 only for linux hosts

---

.gitignore
src/server_manager/cloud/digitalocean_api.ts

Fixes the malformed URL for the getDroplets request

Fixes the malformed URL for the getDroplets request

---

src/shadowbox/docker/Dockerfile

This has significant memory improvements.
cc: @bemasc

Upgrade outline-ss-server to v1.1.3

---

src/shadowbox/docker/Dockerfile
src/shadowbox/server/main.ts

- Fixes outline-ss-server
- Rolls out replay protection to 1%
cc: @bemasc

Release attempt 2

---

src/server_manager/web_app/app.ts
src/server_manager/web_app/ui_components/outline-server-settings.js
src/server_manager/web_app/ui_components/outline-server-view.js

* Supercedes #629 and addresses review comments.

Fire metrics request only on user interaction

---

src/shadowbox/docker/Dockerfile
src/shadowbox/package.json
third_party/outline-ss-server/METADATA

Upgrade outline-ss-server to v1.1.5

---

src/shadowbox/package.json

Since this is adding replay protection, it should be a minor version change. instead.

Update server version to 1.3.0

---

src/shadowbox/docker/Dockerfile
src/shadowbox/package.json
third_party/outline-ss-server/METADATA

Updates outline-ss-server to v1.1.6
cc: @bemasc

Release server v1.3.1

---

src/shadowbox/docker/Dockerfile
third_party/outline-ss-server/METADATA

This should have the packet size change now.

Upgrade outline-ss-server to v1.1.7

---

src/shadowbox/server/main.ts

Enables workaround for https://github.com/Jigsaw-Code/outline-server/issues/726

Enable Prometheus admin API

---

src/shadowbox/package.json
third_party/outline-ss-server/METADATA

Release 1.5.2 (o-ss-s 1.3.2)

---

src/shadowbox/package.json
third_party/outline-ss-server/METADATA

This fixes metrics reporting and UDP quota accounting.

Release 1.5.3 (outline-ss-server 1.3.3)

---

src/shadowbox/README.md

fix wrong path in readme

---

src/shadowbox/package.json

Changelog:
* Adds the ability to set individual data limits for each access key

Release Shadowbox version 1.6.0

---

src/server_manager/install_scripts/install_server.sh

This should help us to debug mysterious installation failures.

Provide more detailed logs if setup fails

---

src/server_manager/install_scripts/install_server.sh

Print a warning if the hostname or IP is invalid

---

src/metrics_server/test_integration_action.sh
src/server_manager/electron_app/build_action.sh
src/server_manager/install_scripts/do_install_server.sh
src/server_manager/install_scripts/install_server.sh
src/server_manager/scripts/fill_packaging_opts.sh
src/server_manager/web_app/build_install_script_action.sh
src/shadowbox/scripts/update_mmdb.sh

Running "shellcheck", and attempting to comply with the shell script
style guide, required hundreds of trivial changes, and a small number of
nontrivial ones.  For ease of review, this PR includes only the
nontrivial changes.

Substantive shell script cleanups

---

scripts/do_action.sh
src/server_manager/install_scripts/do_install_server.sh
src/server_manager/install_scripts/install_server.sh
src/shadowbox/docker/run_action.sh
src/shadowbox/integration_test/test.sh

These are slightly nontrivial shell cleanups discovered in the course of
attempting shellcheck compliance.

Slightly nontrivial shell cleanup

---

.gitignore
README.md
package.json
scripts/shellcheck.sh
src/server_manager/web_app/ui_components/licenses/README.md
src/server_manager/web_app/ui_components/licenses/licenses.txt

Remove lingering mentions of Bower

---

src/server_manager/install_scripts/install_server.sh

Add a fallback IP check URL

---

src/server_manager/web_app/ui_components/app-root.js

- Moves server list templates to separate functions for readability
- Fixes unnecessary 2-way binding
- Removes unnecessary computed properties

Clean up Server list template

---

src/server_manager/web_app/app.ts
src/server_manager/web_app/ui_components/outline-server-view.js

Fix #854
Tested:
Successfully added and removed both manual and managed servers correctly.

Pass the id of the server to remove to event listeners

---

src/server_manager/package.json

This is so we can release the fix to #854

Bump the manager to version 1.7.1 after the server destruction bugfix

---

src/server_manager/package.json

Bumps the minor version due to new language additions (`kk`, `my`).

Increase manager version

---

src/server_manager/web_app/digitalocean_account.ts

Also includes safer bash quoting of the other environment variables.
Fixes #930

Escape unicode characters in the server name

---

src/server_manager/web_app/ui_components/outline-intro-step.js

This was accidentally removed in #944.  Oops.

Restore lost AWS instruction card

---

.github/workflows/test.yml
README.md
package.json

client: https://github.com/Jigsaw-Code/outline-client/pull/1081

add yarn actions, fix ShadowsocksConfig macro, webpack bin

---

src/shadowbox/server/manager_service.spec.ts
src/shadowbox/server/manager_service.ts

This ensures that unauthorized requests never reach the routing step.

Add a pre-routing filter

---

src/server_manager/base.webpack.js
src/server_manager/web_app/ui_components/outline-intro-step.ts

"Advanced" GCP flow (now legacy) is available by setting
GCP_AUTH_ENABLED=false.

chore(manager): show the GCP magic flow by default

---

src/server_manager/messages/fa.json
src/server_manager/messages/it.json
src/server_manager/messages/kk.json

fix(manager): 🌐 update some translation texts

---

src/server_manager/install_scripts/install_server.sh
src/shadowbox/integration_test/client/Dockerfile

I had to fix the integration test in the way.

feat(server): increase TLS key size

---

src/server_manager/README.md
src/server_manager/cloud/digitalocean_api.ts
src/server_manager/electron_app/build.action.sh
src/server_manager/install_scripts/do_install_server.sh
src/server_manager/web_app/digitalocean_account.ts

Upgrade to use image `docker-20-04`. Also enable the web console to make it easy to SSH into the machine.

feat(manager): upgrade DigitalOcean image

---

src/server_manager/package.json

to be merged once we update the links in the invitation flow @jyyi1

chore: update package.json to set version as 1.12.0

---

src/shadowbox/CHANGELOG.md

We don't have a good place to put server release changes. I thought this could work well. Thoughts?

chore(server): create server CHANGELOG

---

src/shadowbox/README.md

fix: fixed the rename command.

---

src/shadowbox/README.md

I forget to add this example in #1142 PR, my bad 😅

docs(server): add getAccessKey method example

---

src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts
src/sentry_webhook/post_sentry_event_to_salesforce.ts

The fields being replaced here are no longer used. I'm updating them here with the new values.

chore(sentry_webhook): update Salesforce values

---

src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts
src/sentry_webhook/post_sentry_event_to_salesforce.ts

Rolling back #1419. This is a likely culprit of Salesforce not creating cases.

fix(sentry_webhook): rollback Salesforce value changes

---

.github/workflows/build_and_test_debug.yml
src/server_manager/install_scripts/install_server.sh

This fixes https://github.com/Jigsaw-Code/outline-server/issues/1234

fix(server): make temp file names longer

---

src/shadowbox/docker/Dockerfile
src/shadowbox/docker/build.action.sh
src/shadowbox/package.json
src/shadowbox/server/main.ts
src/shadowbox/server/manager_service.ts
src/shadowbox/server/shared_metrics.spec.ts
src/shadowbox/server/shared_metrics.ts
src/shadowbox/server/version.ts
src/shadowbox/webpack.config.js

This will help us do releases without having to change source code.

chore(server): inject version at build time

---

src/shadowbox/model/errors.ts
src/shadowbox/server/server_access_key.spec.ts
src/shadowbox/server/server_access_key.ts

fix(server): the provided password must use unique value

---

src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts
src/sentry_webhook/post_sentry_event_to_salesforce.ts

I thought I had pushed this commit to #1510 before merging, but clearly I did not.

chore(sentry_webhook): update UAT record ID

---

src/shadowbox/server/shared_metrics.spec.ts
src/shadowbox/server/shared_metrics.ts

I accidentally merged #1550 which was merging into another branch I had to abandon.
This one's properly going into master. Please take another look.

feat(server): add ASN metric to opt-in server usage report
