Jigsaw-Code/outline-server

src/server_manager/electron_app/digital_ocean_modifications.ts
Injects CSS to DigitalOcean OAuth page, as query selection is now working anymore due to asynchronous loading.
=> Fix DigitalOcean OAuth UI

.travis.yml, src/server_manager/electron_app/config.json, src/server_manager/package.json
* Adds macOS manager to Travis daily build.
* Increases the app's version number.
=> Prepare for macOS release

src/server_manager/web_app/app.ts, src/server_manager/web_app/digitalocean_server.ts
Add confirmation before automatically deleting server on failed installs.
In the past, if a server failed to install (either a server-side issue, or a client side network/firewall issue) we would immediately delete the droplet and show an error asking the user if they would like to submit feedback.  Now, to avoid accidentally deleting already working servers, we show a confirmation message with delete and try again options (try again may be useful if the problem is client-side):
We removed the "Submit Feedback" action from this dialog, because if the user clicked submit feedback it wasn't clear what should happen after the feedback screen completes (do they still have the droplet?  what screen should they see?).  Users can already submit feedback via the settings drawer so this isn't much …
=> Add confirmation before automatically deleting server on failed installs

src/server_manager/install_scripts/install_server.sh, src/server_manager/package.json
https://github.com/Jigsaw-Code/outline-server/pull/109 broke the DigitalOcean installer; it turns out the CloudInit environment has no concept of users and groups:
* no `$USER` environment variable
* no `docker` group
My solution is to use `$UID` to test whether we're running as `root` and, if so, to run Docker commands without the help of `sg`. The latter part was surprisingly difficult: I spent several hours unsuccessfully trying to extend `safe_docker` to "do nothing" when called by root. The problem is **escaping parameters with spaces**; to avoid this headache (BTW, escaping is subtly different in the shell used by the CloudInit environment), I introduced a `DOCKER_CMD` which is set to plain old `docker` for root and `safe_docker` for all other users  - even then, you'll see I had to …
=> fix digitalocean installer

release/release_data.json
Turns out the old auto-update system shows the new version number. 100 looks weird and may be alarming to some users. Instead, use 1.1.0 (which will surely come soon for real anyway).
@alalamav Merging TBR
=> less extreme message for auto-update migration

src/server_manager/install_scripts/install_server.sh, src/server_manager/ui_components/outline-manual-server-entry.html
* Prints the advanced install script output as a single green line to make it easier to copy.
* Updates the advanced mode input placeholder.
=> Collapse advanced install output into a single line

src/server_manager/install_scripts/install_server.sh
Fixes firewall detection when the user is root, as the `safe_docker` function would have not been defined.
=> Replace safe_docker with dynamic DOCKER_CMD

src/server_manager/package.json
* Updates to 1.1.1 for consistency with the deprecated update mechanism.
=> Bump version number to v1.1.1

src/server_manager/ui_components/outline-server-view.html, src/server_manager/ui_components/outline-share-dialog.html
This is useful because it allows the Android client to distinguish invite URLs from non-invite URLs.
Blocked by https://github.com/Jigsaw-Code/outline-website/pull/86.
See also https://github.com/Jigsaw-Code/outline-client/pull/147.
=> Switch invite link from index.html to invite.html

src/shadowbox/infrastructure/ip_location.spec.ts, src/shadowbox/infrastructure/ip_location.ts
I'm seeing the ipinfo.io-based test fail from time to time; since it's not used anywhere - or the caching lookup - let's remove. Also a couple of tiny TypeScript things since this code is fresh in my mind.
=> remove the unused geo ip lookups

src/server_manager/electron_app/index.ts, src/server_manager/electron_app/package_linux_action.sh, src/server_manager/electron_app/package_macos_action.sh, src/server_manager/electron_app/package_only_windows_action.sh, src/server_manager/electron_app/release_windows_action.sh
Dammit, these weren't working for two reasons:
- need to "unpack" the images (just like we do in the client for the binaries we launch)
- `showItem` is needed for Windows (and no `file://` prefix)
This time, it's been tested on macOS, Linux, and Windows with the final binaries (not just `yarn do electron/run`.
=> fix the "show me where" links

src/server_manager/infrastructure/errors.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/shadowbox_server.ts
Lots of work we could do on our error reporting...but this should reduce the noise we've been seeing in Sentry due to network errors on data usage fetches.
=> suppress network errors for data usage requests

src/server_manager/install_scripts/install_server.sh
Looks like this fails when running via the server manager magic install:
https://github.com/Jigsaw-Code/outline-server/pull/226/files
=> ROLLBACK firewall warning fix

src/shadowbox/infrastructure/logging.ts
This kind of copies the Google standard and makes the lines more useful, specially when logs are mixed between different processes. Example:
```
I2018-08-16T16:46:21.577Z 167288 main.js:86] Starting...
```
=> Enhance log messages

src/server_manager/index.html, src/server_manager/package.json, yarn.lock
Magic mode and advanced modes seem to work fine with Electron 2; it complained about our content security policy which turned out to be completely bogus so I updated it.
BTW, I tried electron-updater 3.x but ran into compile errors. I don't think it's ready for primetime yet.
=> migrate to Electron 2.x

src/shadowbox/infrastructure/filesystem_text_file.ts, src/shadowbox/infrastructure/follow_redirects.ts, src/shadowbox/infrastructure/get_port.ts, src/shadowbox/infrastructure/logging.ts, src/shadowbox/model/metrics.ts, src/shadowbox/server/libev_shadowsocks_server.ts, src/shadowbox/server/main.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/metrics.spec.ts, src/shadowbox/server/metrics.ts, src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts, src/shadowbox/types/node.d.ts
We already have a "Manager" service and "Managed" here doesn't mean much. Now `ServerAccessKey` means the `AccessKey` implementation used by the Server. This should avoid some confusion on the code and make it more readable.
=> Rename Managed -> Server

src/server_manager/ui_components/outline-feedback-dialog.html, src/server_manager/web_app/app.ts
* Re-styles the feedback form.
* Adds more concrete feedback categories.
* Displays a dropdown to select a cloud provider when a relevant category is selected.
* Displays a disclaimer that we are only able to respond in English when the user enters their email.
FYI, @sandrigo @ohnocassio.
=> Feedback form improvements

src/server_manager/install_scripts/do_install_server.sh
Tested this just now with a DigitalOcean server in London, seems to work great.
=> enable BBR on new DigitalOcean droplets

src/shadowbox/docker/Dockerfile, src/shadowbox/integration_test/client/Dockerfile, src/shadowbox/integration_test/test.sh, src/shadowbox/model/shadowsocks_server.ts, src/shadowbox/scripts/install_shadowsocks.sh, src/shadowbox/server/libev_shadowsocks_server.ts, src/shadowbox/server/main.ts, src/shadowbox/server/mocks/mocks.ts, src/shadowbox/server/outline_shadowsocks_server.ts, src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts, src/shadowbox/server/shared_metrics.spec.ts, src/shadowbox/server/shared_metrics.ts
This is the last PR for adding the Go server.
Once we fully rollout the Prometheus change, we can merge this PR and start the new rollout.
Then the only thing left will be to tweak ServerAccessKeyRepository to always use the same port to launch single port.
=> Add outline-ss-server with rollout

src/shadowbox/infrastructure/get_port.spec.ts, src/shadowbox/infrastructure/get_port.ts, src/shadowbox/server/main.ts, src/shadowbox/server/manager_metrics.ts, yarn.lock
Also, fix the legacy metric asynchronous call, which we were not waiting for, and remove scraping of `outline-ss-server` when not enabled, which just pollutes the logs.
Fixes #279
=> Test ports by opening them

src/shadowbox/server/outline_shadowsocks_server.ts
This is a way to gracefully degrade if someone edited the config and added an unsafe cipher that outline-ss-server doesn't support.
=> Ignore invalid ciphers

src/shadowbox/integration_test/test.sh, src/shadowbox/server/libev_shadowsocks_server.ts, src/shadowbox/server/manager_service.ts
This PR does two things:
- Adds a test that disallows errors in the logs. This captures the issue I'm seeing with outline-ss-server, and a small issue with ss-libev that pollutes the logs
- Fixes the update for ss-libev
@trevj FYI
=> Fix update

src/server_manager/ui_components/outline-server-view.html
Added sort access keys by name to make it easy to find them when managing many users.
---
Currently keys are sorted by creation dates.
When we have many users, it makes it easy manage keys if it's sorted by name. E.g when you have multiple orgs/departments on one server, you can have:
```
cfa-david
...
alpha-larry
...
jigsaw-george
```
Above by sorting by name would know where to scroll to to find it without introducing any new "features" e.g search nor trying to remember when you created the key:
```
alpha-larry
...
cfa-david
...
jigsaw-george
```
Related: #293
=> Sort access keys by name

src/shadowbox/server/manager_metrics.ts, src/shadowbox/server/shared_metrics.ts
This change will report all the traffic between the proxy and the target, since that's the actual protected traffic.
I added some extra comments on measured flows, since that's quite confusing.
=> Fix reported metrics

src/shadowbox/integration_test/test.sh
Looks like the integration test is currently flaky on Travis. Since there's no way to retrieve the log, let's print it to stdout.
Followup to:
https://github.com/Jigsaw-Code/outline-server/pull/290
=> print shadowbox logs on integration test failures

src/shadowbox/docker/cmd.sh
Files created by Node, outline-ss-server or prometheus will not be readable by other users
This partially addresses https://github.com/Jigsaw-Code/outline-cure53/issues/9, since there are still files created at installation (such as access.txt or the TLS key).
=> Add umask to Shadowbox

src/server_manager/install_scripts/install_server.sh, src/server_manager/ui_components/outline-manual-server-entry.html, src/shadowbox/README.md
This PR puts all Outline files under /var/lib/outline, owned by user `root`, and sets the sticky bit to preserve the ACL for subdirectories.
This partially addresses https://github.com/Jigsaw-Code/outline-cure53/issues/9. The rest of the fix is at https://github.com/Jigsaw-Code/outline-server/pull/311.
This fixes https://github.com/Jigsaw-Code/outline-cure53/issues/2, since everything runs as root and there's no need to add the user to the docker group.
Notice that now the script has to run as root
In the process I fixed the access key port number that was not showing.
=> Move shadowbox directory, make it non-world readable, require sudo for installer

src/server_manager/web_app/management_urls.spec.ts, src/server_manager/web_app/management_urls.ts
Prior to https://github.com/Jigsaw-Code/outline-server/pull/315 we stripped whitespace from manual server configs input into the text box; this restores that behaviour (my mistake).
Fixes:
https://github.com/Jigsaw-Code/outline-server/issues/322
=> strip whitespace from server configs, like we used to

.travis.yml
Just a little thing I noticed while tests were flaky recently:
- if the build or tests are flaky then the tag stage won't get run and we lose out on that day's snapshot
- it's wasteful building and testing when the only function of the cronjob is to tag - this will get our daily builds out a little faster
=> when invoked by cron, only run the tag stage

.travis.yml
Looks like https://github.com/Jigsaw-Code/outline-server/pull/342 is not doing exactly what I'd like:
https://travis-ci.org/Jigsaw-Code/outline-server/jobs/465463017
Looks like `travis_terminate` is only good for terminating stages, not entire builds. Let's do it the old-fashioned way (no comment required now, I think).
=> do not build and test for cron builds (take two)

.travis.yml
Huh, never noticed before that I forgot include the `name:` for these two stages. I think this is preventing https://github.com/Jigsaw-Code/outline-server/pull/346 from working.
=> fix broken stages section in .travis.yml

src/sentry_webhook/README.md, src/sentry_webhook/build_action.sh, src/sentry_webhook/deploy_action.sh, src/sentry_webhook/index.ts, src/sentry_webhook/package.json, src/sentry_webhook/post_sentry_event_to_salesforce.ts, src/sentry_webhook/tsconfig.json, yarn.lock
* The cloud function and enclosing package follow the example of `metrics_server`.
* It receives Sentry events via webhook integration, extracts the data and posts it as form data to Salesforce.
* Infers whether the event is from development or production and posts to the corresponding Salesforce endpoint.
=> Implement cloud function to post Sentry events to Salesforce

src/shadowbox/docker/Dockerfile, src/shadowbox/server/main.ts
I'm upgrading the node and outline-ss-server versions and also making a change that should fix https://github.com/Jigsaw-Code/outline-server/issues/341.
I expect to be able to release this today.
=> Upgrades and localhost fix

src/shadowbox/server/main.ts
Single port cannot be enable without fixing this.
=> Dedupe key ports before reserving

src/shadowbox/README.md, src/shadowbox/docker/run_action.sh, src/shadowbox/integration_test/test.sh, src/shadowbox/scripts/make_test_certificate.sh, src/shadowbox/server/api.yml, src/shadowbox/server/manager_service.ts, src/shadowbox/server/run_action.sh
This creates an OpenAPI 3.0 spec for our management API, which can be used to document our API and generate client code.
You can see the new API documentation from the spec here: https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/fortuna-api/src/shadowbox/server/api.yml
=> Add API spec

src/shadowbox/docker/Dockerfile, src/shadowbox/integration_test/test.sh
* Updates outline-ss-server to [v1.0.4](https://github.com/Jigsaw-Code/outline-ss-server/releases/tag/v1.0.4).
* Modifies the integration test to fetch a public URL through shadowbox, since v1.0.4 restricts access to the the server's LAN. The integration test validates that the server's LAN is indeed not accessible.
=> Update outline-ss-server to v1.0.4

src/server_manager/install_scripts/install_server.sh, src/shadowbox/README.md
This will allow advanced users to easily specify a domain name for their server, and what ports to use.
Example use:
```
sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" \
install_server.sh --hostname=outline.mydomain.com --keys-port=443 --api-port=8443
```
=> Add flags for hostname and ports

src/server_manager/bower.json, src/server_manager/ui_components/licenses/licenses.txt, src/server_manager/ui_components/outline-server-settings.html
This changes the toggle button to be a checkbox, which is hopefully more clear of an indicator of whether or not metrics sharing is enabled.
=> Clarify whether or not a server is sharing metrics data

src/shadowbox/README.md, src/shadowbox/docker/run_action.sh, src/shadowbox/model/access_key.ts, src/shadowbox/model/shadowsocks_server.ts, src/shadowbox/server/api.yml, src/shadowbox/server/main.ts, src/shadowbox/server/manager_metrics.spec.ts, src/shadowbox/server/manager_metrics.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/mocks/mocks.ts, src/shadowbox/server/outline_shadowsocks_server.ts, src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts
* Implements support for access key (outbound) data transfer quotas over a sliding time window, expressed in hours.
* Enforces access keys quotas hourly by comparing their usage over the set time window to the set quota. Disables over-quota access keys at the Shadowsocks server and enables them once they are under-quota.
* Exposes APIs to set and remove access key quotas through the management service.
* `PUT /access-key/{id}/quota`
* `DELETE /access-key/{id}/quota`
* Adds functionality to query per-access-key hourly data transfer usage through Prometheus metrics.
* Refactors `ServerAccessKeyRepository` to keep access keys in memory and improves asynchronous interface.
* Implements unit tests for every new method.
=> Access key quotas

src/server_manager/install_scripts/install_server.sh
Fixes https://github.com/Jigsaw-Code/outline-server/issues/459
`declare -g` only works in bash 4.2 and above, which some old versions of CentOS don't have.  Our use of it is pretty unnecessary, there's no reason to be messing around with scope like that in a bash script anyways.
Tested by running the following script on bash 4.1 (built from source from ftp.gnu.org/gnu/bash/bash-4.1.tar.gz) and ensuring the output is "abc" then "def".
```
function f1 () {
echo "${MY_VAR}"
}
function f2() {
MYVAR="def"
}
function main () {
declare MYVAR="abc"
f1
f2
f1
}
main
```
=> Avoid declare -g for old bash installs

src/server_manager/electron_app/index.ts
* We have seen failures with DigialOcean API requests due to same-origin policy. It seems like DO stopped sending 'Access-Control-Allow-Origin' headers in responses to some endpoints (`/v2/droplets`).
* As a workaround, we inject the 'Allow-Origin' header with our origin to DO API responses.
* Fixes #466.
=> Inject 'Allow-Origin' header to DigitalOcean API responses

src/server_manager/ui_components/outline-server-view.html, src/server_manager/web_app/app.ts
* Doesn't change selected tab to Connections 
* Makes Connections the default tab of the server view
=> Don't change to connections tab after changing server name

src/server_manager/electron_app/index.ts
* DigitalOcean API OPTIONS requests are failing with status code 403. 
* As a workaround, synthesize successful preflight responses by injecting CORS headers and modifying the reponse status code to 200.
* Fixes #476.
=> Synthesize DigitalOcean API CORS preflight responses

src/server_manager/model/server.ts, src/shadowbox/README.md, src/shadowbox/infrastructure/prometheus_scraper.ts, src/shadowbox/model/access_key.ts, src/shadowbox/model/errors.ts, src/shadowbox/model/metrics.ts, src/shadowbox/server/api.yml, src/shadowbox/server/main.ts, src/shadowbox/server/manager_metrics.spec.ts, src/shadowbox/server/manager_metrics.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/mocks/mocks.ts, src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts, src/shadowbox/server/server_config.ts
* Implements a server data usage timeframe, used to report access key data usage metrics (`GET /metrics/transfer`) and to enforce access key data limits.
* Exposes an API endpoint, `PUT /server/data-usage-timeframe`, to configure this value. The default is 30 days for backwards compatibility with the existing `GET metrics/transfer` timeframe.
* The data usage timeframe can be retrieved through the `GET /server` endpoint.
* Previously, access key data limits supported individual timeframes per key in order to calculate data utlization. The timeframe is now shared between all access keys with data limits.
* Updates the `PUT /access-key/[:id]/data-limit` API to reflect the shared timeframe.
=> Server data usage timeframe

src/shadowbox/docker/Dockerfile
* See https://github.com/Jigsaw-Code/outline-ss-server/releases/tag/v1.0.7
* Docker image node:8.15.0 is the latest one that is signed. See https://github.com/nodejs/docker-node/issues/1065.
=> Update outline-ss-server to v1.0.7 and docker node to v8.15.0

src/shadowbox/server/main.ts
@fortuna re: https://github.com/Jigsaw-Code/outline-server/issues/341
For some reasons there's a regression of this issue and unfortunately I'm unable to figure out the primary cause or the source of the ip.
However, setting a static localhost works both
=> [fix]: regressing ip

src/shadowbox/infrastructure/prometheus_scraper.ts, src/shadowbox/server/server_access_key.ts
* This error in the canary server suggests that Promehteus is not ready to receive queries when the access key repository starts, resulting the main process to abort.
```
E2019-09-18T06:47:57.987Z 7 main.js:166] Error: Got error 503
at ClientRequest.http.get (/root/shadowbox/app/infrastructure/prometheus_scraper.js:40:28)
at Object.onceWrapper (events.js:315:30)
at emitOne (events.js:116:13)
at ClientRequest.emit (events.js:211:7)
at HTTPParser.parserOnIncomingClient (_http_client.js:558:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
at Socket.socketOnData (_http_client.js:454:20)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
```
* `ServerAccessKeyRepository.start` does not throw.
* Query `/api/v1/status/flags` …
=> Fix waiting for Prometheus ready

src/shadowbox/server/main.ts
This can happen after an access key has been deleted.
=> Fix unhandled rejection

src/shadowbox/model/errors.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/mocks/mocks.ts, src/shadowbox/server/server_access_key.ts
* Follow up to a review comment of #485.
* Adds a user type guard to the manager API request parameters.
* Changes the type of `RequestType.params` to  `RequestParams|{}` to reflect incoming untyped data.
* `s/errors.InvalidDataLimitTimeframe/errors.InvalidDataUsageTimeframe`
FYI, @fortuna, @JonathanDCohen.
=> Improve type safety of manager service request parameters

src/server_manager/electron_app/index.ts
Fixes a bug that would prevent the user from installing the Outline macOS client in the "Get Connected" flow.
=> Allow navigation to the Mac App Store

yarn.lock
This avoids https://nvd.nist.gov/vuln/detail/CVE-2019-17592
It's likely low risk for us, but an easy fix anyways.
=> Upgrade csv-parse

src/shadowbox/integration_test/run_action.sh, src/shadowbox/integration_test/test.sh
The integration test has been flaking from time to time on Travis with no obvious failures, indicating this is happening unexpectedly outside a `fail` call.  `set -x` will help us diagnose when it happens again.
=> Set -x in the integration test

src/server_manager/package.json
Minor version bumped due to new functionality of changing the port
number for new access keys.
=> Increase Server Manager version to 1.3.0

src/server_manager/install_scripts/do_install_server.sh
Hello,
This is an update for #143. DigitalOcean phased out their legacy metrics client and changed the location of the install script.
https://www.digitalocean.com/docs/monitoring/quickstart/#enable-the-digitalocean-agent-on-existing-droplets
I've updated the URL to the `install.sh` script. `bash` was required for installation to succeed. The script from DO automates adding DO apt repositories and installing `do-agent`. I stood up several Outline servers to test that it is working correctly. FWIW, I didn't see any race conditions as noted in https://github.com/Jigsaw-Code/outline-server/pull/143#issuecomment-406316212.
Before: 
After: 
```
> cat /var/log/apt/history.log
...
Start-Date: 2019-10-30  18:43:36
Commandline: apt-get -qq install -y do-agent
Install: do-agent:amd64 (3.5.6) …
```
=> Upgrade to the new version of Digital Ocean's Metrics agent

src/server_manager/package.json, yarn.lock
electron-builder has trouble finding a set version of electron when it is specified as ^7.0.0.  Since 7.0.0 is the latest electron version, we can fix at that version.  We will set ^7.0.0 when more become available.
=> Fix at electron v7.0.0

.travis.yml
* electron-builder v21+ requires macOS 10.13.6+ for signing to work.
* Specify the macOS image on Travis: `osx_image: xcode10.1` runs in macOS 10.13.6.
=> Specify macOS image in Travis

src/server_manager/model/server.ts, src/shadowbox/README.md, src/shadowbox/model/access_key.ts, src/shadowbox/model/errors.ts, src/shadowbox/server/api.yml, src/shadowbox/server/main.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts, src/shadowbox/server/server_config.ts
* Removes the `/server/data-usage-timeframe` API.
* Removes the `dataUsageTimeframe` property from the server config and access key repository.
* Removes associated unit tests.
* Note that metrics model still defines `DataUsageTimeframe`, which is used by `ManagerMetrics.getOutboundByteTransfer`. This flexibility will be useful for some implementations of data limits.
=> Deprecate server data usage timeframe API

src/shadowbox/README.md, src/shadowbox/model/access_key.ts, src/shadowbox/server/api.yml, src/shadowbox/server/main.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts, src/shadowbox/server/server_config.ts
* Replaces individual access key data limits with a server data limit, applied to all access keys.
* Exposes `PUT, DELETE /access-key-data-limit` APIs for configuring the data limit. 
* These are in an `/experimental` path until the feature is validated.
* Persists the access key data limit in the server config.
* Returns the data limit in the `/server` API.
=> Server data limit

src/shadowbox/server/manager_service.ts
This was accidentally removed in #537.
=> Return the port for new access keys from GET /server.  

src/shadowbox/docker/Dockerfile, src/shadowbox/scripts/update_mmdb.sh
* `for x in {a..b}` is bash-only, and alpine's default shell is `dash`.
* Use `[[` instead of `((` for the branch
* Make sure to update to GNU coreutils in the image in order to use
`date --date`
* Also updates to use `outline-ss-server` v1.0.8
=> Fix update_mmdb and the Docker image to work on Alpine

src/server_manager/install_scripts/install_server.sh
* The shadowbox server config JSON file was not formatted correctly due incorrectly appending the hostname to the `config` array, which caused `$IFS` in `join` not to take effect.
* Fixes #538.
=> Fix formatting in shadowbox config

src/server_manager/install_scripts/install_server.sh
It looks like the watchtower repo was renamed to `containrrr/watchtower` sometime ago and the old `v2tec/watchtower` image hasn't been updated for over a year.
=> Update the watchtower image name

jasmine.json, src/metrics_server/README.md, src/metrics_server/app_dev.yaml, src/metrics_server/app_prod.yaml, src/metrics_server/config_dev.json, src/metrics_server/config_test.json, src/metrics_server/connection_metrics.spec.ts, src/metrics_server/connection_metrics.ts, src/metrics_server/deploy_dev_action.sh, src/metrics_server/deploy_prod_action.sh, src/metrics_server/dispatch.yaml, src/metrics_server/feature_metrics.spec.ts, src/metrics_server/feature_metrics.ts, src/metrics_server/index.ts, src/metrics_server/infrastructure/table.ts, src/metrics_server/model.ts, src/metrics_server/package.json, src/metrics_server/post_feature_metrics_report.ts, src/metrics_server/post_server_report.ts, src/metrics_server/run_action.sh, src/metrics_server/test_action.sh, src/metrics_server/test_integration_action.sh, src/server_manager/electron_app/run_action.sh, src/shadowbox/docker/cmd.sh, src/shadowbox/docker/run_action.sh, src/shadowbox/server/main.ts, src/shadowbox/server/run_action.sh, src/shadowbox/server/shared_metrics.spec.ts, src/shadowbox/server/shared_metrics.ts
`metrics_server`
* Migrates the metrics server from Cloud Functions to App Engine.
* Configures `dev` and `prod` environments (accessible only through HTTPs).
* Exposes an endpoint to collect feature metrics.
* Adds unit tests for existing and new code.
* Adds an integration test for connection and feature metrics.
`shadowbox`
* Reports daily feature usage when the server has opted-in to sharing metrics. Currently, only reports metrics for the data limits feature.
* Adds feature metrics unit tests.
* Updates the production metrics endpoint to `https://prod.metrics.getoutline.org`.
=> Feature metrics

src/shadowbox/docker/run_action.sh
A few fixes:
- `SB_IMAGE` is undefined in the echo call
- `SB_METRICS_URL` is unspecified
- If you run a second time, the touch command fails if you added a key. That's because the config is written as root.
I'm fixing those, and introducing the concept of a `RUN_ID`. Each run will write to a different directory, but if you want persistence across runs, you can specify it, like this:
```
RUN_ID=mytest yarn do shadowbox/docker/run
```
Which will write to `/tmp/outline/mytest`.
=> Fix docker run action

src/shadowbox/server/main.ts, src/shadowbox/server/outline_shadowsocks_server.ts
I'm adding the rollout with 0% for now, but anyone can enabled it by adding this to `shadowbox_server_config.json`:
```
"rollouts":[{"id":"replay-protection","enabled":true}]
```
When enabled, you will see the following output:
```
I2020-02-28T00:39:04.251Z 11 main.js:130] Replay protection enabled: true
```
And you can use `ps` to verify that `outline-ss-server` is running with the right flag:
```
$ ps a | grep outline-ss-server | grep --invert grep 
251367 pts/0    Sl+    0:00 /root/shadowbox/bin/outline-ss-server -config /root/shadowbox/persisted-state/outline-ss-server/config.yml -metrics 127.0.0.1:9092 -ip_country_db /var/lib/libmaxminddb/ip-country.mmdb -verbose --replay_history=10000
```
cc: @bemasc @JonathanDCohen
=> Add rollout for the replay protection

package.json
We don't want prettier to override tslint for TS files.
=> Only lint HTML files with prettier

src/server_manager/electron_app/release/notarize.js
* The package action does not sign binaries; however, the "afterSign" hook still runs and app notarization fails due to missing signing credentials.
* Fixes the macOS packaging action by skipping notarization when the app is unsigned.
=> Skip app notarization when packaging

src/server_manager/ui_components/outline-validated-input.html
=> Expand buttons when their label is too wide to fit

src/metrics_server/package.json, src/server_manager/package.json, src/server_manager/ui_components/outline-server-view.html, yarn.lock
After out meeting online, this implements the minimal functionality of selecting a newly made key, and defers other UX improvements until we can do them all at once.
Pushed this in a new branch to keep history clean.  This PR supersedes https://github.com/Jigsaw-Code/outline-server/pull/569
=> Select newly added keys

src/server_manager/package.json, yarn.lock
- Packaging on CI is failing due to electron-builder not being able to infer the electron's version.
- Pins the electron version to 7.0.1.
- Updates electron-builder to 22.4.0 (unrelated to the failure).
- For more information see https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
=> Pin electron version to 7.0.1; update electron-builder to 22.4.0

src/server_manager/index.html, src/server_manager/ui_components/app-root.html, src/server_manager/ui_components/style.css, tsconfig.json
This makes the code more readable, and the IDE can warn about errors.
Furthermore, the fact that AppRoot was not a class always got in the way of converting to Typescript. This will make a future conversion easier.
=> Make AppRoot a class

src/server_manager/bower.json, src/server_manager/index.html, src/server_manager/infrastructure/i18n.spec.ts, src/server_manager/infrastructure/i18n.ts, src/server_manager/ui_components/app-root.html, src/server_manager/web_app/main.ts
This:
- Creates a i18n library with tests
- Moves logic out of ui component (it shouldn't be there)
- Removes another entry point from index.html
I'm aiming to have one Javascript entrypoint and no cross-dependency between entry points. The current hidden dependencies makes migration hard.
Notice that this pushes more logic into Typescript.
cc: @JonathanDCohen @mpmcroy
=> Clean up language logic

package.json, src/server_manager/package.json, src/server_manager/ui_components/outline-server-view.html, src/server_manager/web_app/app.spec.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/main.ts, tsconfig.json, yarn.lock
This is an issue I ran into when migrating to Webpack. We are depending on some Node.js code in browser code. I believe the only reason why it works is because browserify must insert some polyfill. Still, it's better to not depend on that, especially given browser alternatives are available.
After this change, I believe I'll be able to migrate to webpack, which may allow us to use node_modules dependencies in the html javascript and move towards a single javascript entry point.
=> Stop depending on Node code in the browser code

src/server_manager/infrastructure/sentry.spec.ts, src/server_manager/infrastructure/sentry.ts, src/server_manager/web_app/main.ts
Master is broken, so we should fix this as soon as possible. At least it wasn't working with the DSN I'm using and the ones I found in the project page. On side effect of the breakage is not seeing the DO servers in the manager (because of the failure).
We may want to re-release. This may fix the issue you were seeing on Windows.
=> Fix getSentryApiUrl

src/server_manager/index.html, src/server_manager/package.json, src/server_manager/web_app/build_action.sh, src/server_manager/webpack.config.js, tsconfig.json, yarn.lock
There many advantages to using webpack. 
- Simplifies our build.
- We can target the electron-renderer, electron-preload or electron-main, and the right environment is set up automatically.
- We can use the mode optionto get optimized code or not.
- There's support for watching and for [hot reload](https://webpack.js.org/concepts/hot-module-replacement/), but I need to investigate that.
- It's possible to depend on node_modules from the Polymer JS using [polymer-webpack-loader](https://github.com/webpack-contrib/polymer-webpack-loader), which will remove the need for the browserify call, but I still need to get that working.
- It's possible to depend on html, css, etc from Typescript, which will help migration to Polymer3
- It's what the industry uses now, and there's plenty of tooling …
=> Use Webpack

src/server_manager/web_app/build_action.sh
- Fixes the webpack build for cygwin on Windows by using relative paths.
- Since we're dropping Browserify on #632 - this change allows master to build until that PR is merged.
=> Use relative paths in webpack build

src/server_manager/electron_app/index.ts, src/server_manager/electron_app/preload.ts, src/server_manager/package.json, yarn.lock
- Updates `@sentry/electron` to v1.3.0.
- Breadcrumb configuration is now split between the renderer and main processes.
- Fixes an issue in Windows where the server returned an empty response when using the `ingest.sentry.io` as the domain name for the API key.
=> Update @sentry/electron to v1.3.0

src/server_manager/electron_app/index.ts, src/server_manager/electron_app/preload.ts
* `@sentry/electron` v1.3.1 throws an error when it is initialized with an empty DSN.
* Fixes this isssue by only initializing sentry when the `SENTRY_DSN` environment variable is set.
* Tested that submitting feedback is still a no-op when `SENTRY_DSN` is unset.
=> Initialize Sentry only when SENTRY_DSN is set

src/shadowbox/docker/Dockerfile
- Upgrades the shadowbox docker node image to v12.16.3-alpine (amd64)
- Newer docker node images do not have valid content trust, so we pin the image sha256 hash as a workaround.
- Calls the default `yarn` binary, which I verified is at the latest version 1.22.4.
=> Update shadowbox docker node image to v12.16.3

src/shadowbox/package.json, src/shadowbox/server/main.ts, src/shadowbox/server/manager_service.ts, yarn.lock
- Updates restify and @types/restify to v8.
- Replaces core restify CORS with restify-cors-middleware, as it has been removed from restify. 
- The options we pass are the same as the previous defaults.
- This generates a warning: `restify-cors-middleware@1.1.1" has incorrect peer dependency "restify@2.6.x - 7.x.x"`; however, I haven't seen related runtime errors.
- I'm not sure I fully understand why we need CORS, since we configure it with any origin (`"*"`).
=> Upgrade restify to v8.5.1

src/server_manager/cloud/digitalocean_api.ts, src/server_manager/electron_app/index.ts
This removes the trailing `/` from the calls, and fixes `workaroundDigitalOceanApiCors()`.
Reference: https://github.com/electron/electron/blob/v7.0.1/docs/api/web-request.md#webrequestonheadersreceivedfilter-listener
cc: @mpmcroy
=> Fix DO API

.travis.yml, src/shadowbox/docker/Dockerfile, src/shadowbox/docker/build_action.sh, src/shadowbox/docker/cmd.sh, src/shadowbox/docker/run_action.sh, src/shadowbox/infrastructure/logging.ts, src/shadowbox/server/build_action.sh, src/shadowbox/tsconfig.json, src/shadowbox/webpack.config.js
- Uses webpack to build shadowbox, replacing vanilla `tsc`.
- Builds shadowbox in the docker container since webpack must bundle the image's dependencies and not the host's.
- Supports building for production (default) or development through an environment variable, `BUILD_ENV`.
=> Build shadowbox with webpack

src/shadowbox/docker/Dockerfile, src/shadowbox/package.json, yarn.lock
This makes the first build faster by not copying node_modules and not adding the package.json for all workspaces: 50s vs 128s.
(NOTE: it will have to change with cross-workspace dependencies)
It makes subsequent runs *a lot* faster by not re-running yarn install on every code change: 17s vs 128s.
=> Optimize Dockerfile

src/server_manager/web_app/ui_components/outline-server-view.js
The $$ field is only available in legacy Polymer. This broke when switching to a class.
=> Fix access key creation

src/server_manager/web_app/app.spec.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/display_server.ts, src/server_manager/web_app/main.ts, src/server_manager/web_app/ui_components/app-root.js, src/server_manager/web_app/ui_components/outline-server-view.js, tsconfig.json
We will now get type completion and type check for the code defined in Javascript.
Notice that we can also define types in Javascript and the Typescript code can depend on that. The opposite is not true: Javascript cannot depend on types defined in Typescript code (unless we compile it first).
This gets us most of the way towards type safety, without having to completely convert the classes to Typescript, which will be a lot of work.
Inspiration: https://github.com/daKmoR/type-safe-webcomponents-with-jsdoc
TS support for JSDoc: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc
cc: @JonathanDCohen @mpmcroy
=> Add types to Javascript

.travis.yml, src/shadowbox/docker/Dockerfile, src/shadowbox/docker/build_action.sh
If we don't specify the version, we get a more recent one: `5:19.03.9~3-0~ubuntu-xenial`
This is a failed attempt to fix the broken build, which seems to be related to Buildkit:
- https://github.com/moby/buildkit/issues/606
- https://github.com/moby/buildkit/pull/1397
=> Use latest docker version

src/shadowbox/docker/Dockerfile, src/shadowbox/server/build_action.sh
* Reverts the Docker CMD change in #674.
* watchtower uses the original CMD to restart the image, causing the latest image update to fail.
* Copies `cmd.sh` to the container root directory in order to address this issue.
=> Restore Docker CMD for backwards compatibility

.travis.yml, package.json, src/shadowbox/integration_test/test.sh
A few tweaks to Travis:
- Use `server-` tags instead of `daily-`. This clarifies it's the server, and I want to use that for releases (e.g. `server-v1.2.3`).
- Clarify stage names
- Merge unit and integration tests into a single Test stage to run in parallel
- Use job names instead of env var
This also fixes the docker cleanup and the flakiness of the integration test
cc: @mpmcroy
=> Clarify Travis build

src/server_manager/electron_app/index.ts, src/server_manager/electron_app/preload.ts, src/server_manager/types/preload.d.ts, src/server_manager/web_app/browser_main.ts, src/server_manager/web_app/digitalocean_server.ts, src/server_manager/web_app/manual_server.ts
Use "trust certificate" instead of "whitelist certificate". "Trust" has the right semantics. 
Certificates don't have colors, so putting them in a list of white certificates doesn't make sense, unless we rely on a racist assumption that "white is good/trusted" and "black is bad/not trusted".
=> Use more accurate language for trusting certificates

src/server_manager/web_app/ui_components/outline-server-view.js
Sets flex-grow on access key name element to take up available space
=> Sets flex-grow on access key name element

src/server_manager/web_app/app.ts, src/server_manager/web_app/ui_components/app-root.js, src/server_manager/web_app/ui_components/cloud-install-styles.js, src/server_manager/web_app/ui_components/outline-region-picker-step.js, src/server_manager/web_app/ui_components/outline-region-picker-step.ts
To get ready for multiple cloud "magic" experiences, this updates the region picker with the following:
* Creates a separate view model for the region picker
* Extracts hardcoded list of DigitalOcean regions/flags
* Removes getSelectedRegionId() as per OpenWC [best practices](https://open-wc.org/developing/best-practices.html#upwards-data)
* Adds [workaround](https://github.com/Polymer/lit-element/issues/100) to include cloud-install-styles
* Small cleanups (e.g. binding to checked property)
Caveats: 
* There's a slight performance regression. The updated region picker lags for ~0.5 seconds before showing the available regions.
* The RTL plugin doesn't run on the LitElement CSS. I updated the region picker css to be bi-directional.
**Original**
**Updated (ltr/rtl)**
=> Outline Region Picker refactor

src/shadowbox/docker/Dockerfile, third_party/outline-ss-server/METADATA
This adds protection against server replays and the `shadowsocks_build_info` Prometheus metric with the release version.
There's also a version flag now, so you can run `outline-ss-server -version` to confirm the version you have in the repository.
=> Upgrade outline-ss-server to v1.2.1

src/server_manager/cloud/digitalocean_api.ts
The app is swallowing unauthorized errors (e.g. bad token/expired token) bypassing the connectivity dialog flow. This leaves the user in an unrecoverable state in which they cannot log out or re-login.
This PR catches the 401 error and treats it as a connectivity error, allowing the user to retry or logout.
=> Fix for bad/expired DigitalOcean access token issue

src/server_manager/cloud/digitalocean_api.ts, src/server_manager/web_app/ui_components/app-root.js
The DigitalOcean account connectivity dialog, which pops up when the app encounters CORS and network errors, has two buttons:
* **CANCEL** - closes the dialog and disconnects the users DigitalOcean account
* **RETRY** - retries the DigitalOcean network request
This PR renames the **CANCEL** button to **DISCONNECT** to make it clear to the user that their DigitalOcean account will be disconnected (_since this is happening without the user knowing_).
Original vs Updated screenshots
=> Changes the text on the DO account connectivity dialog 'cancel' button to 'disconnect'

src/server_manager/web_app/app.ts
Some cleanup:
- Converts Promise code to async
- Renames `showServer()` to `showServerManagement()` and `showServerIfHealthy()` to `showServer()`
Borrows from https://github.com/Jigsaw-Code/outline-server/pull/783
More clean up to come, including small product changes. I wanna get rid of `serverBeingCreated`.
/cc @alalamav
=> Clean up some code

src/server_manager/web_app/app.ts
`isManagedServer` already performs the proper runtime check and allows `tsc` to narrow the type.
=> Remove Unneeded Casts

src/shadowbox/server/api.yml
It came up in https://github.com/Jigsaw-Code/outline-server/issues/786 that we're still only documenting the experimental data limits endpoint on reDoc.  This PR deprecates the `experimental/access-key-data-limit` API endpoints and adds the correct ones to the documentation.
See https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Jigsaw-Code/outline-server/cohenjon-default-limit-api/src/shadowbox/server/api.yml#tag/Limit/paths/~1server~1access-key-data-limit/put
=> Document the non-experimental API endpoint for the default data limit

src/server_manager/web_app/app.spec.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/ui_components/app-root.js, src/server_manager/web_app/ui_components/outline-server-progress-step.js, src/server_manager/web_app/ui_components/outline-server-view.js
This PR replaces the single `outline-server-progress-step` from `app-root` with individual progress views in `outline-server-view`.
This will make it easier to display server views since `app-root` (and `app.ts`) will no longer need to maintain logic to show/hide the progress view. The progress view can now be considered a state of the server view (progress/unreachable/healthy).
=> Moves the "server progress view" to the "create server" flow

src/server_manager/model/server.ts, src/server_manager/web_app/app.spec.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/digitalocean_server.ts, src/server_manager/web_app/manual_server.ts, src/server_manager/web_app/shadowbox_server.ts
This adds a stable ID to the server domain model (`server.getId()`). 
* For managed servers, currently only DigitalOcean, we use the droplet ID (aka host ID). 
* For manual servers, we use the management API URL.
This PR also renames the serverId (`server.getServerId()`) to metricsId (`server.getMetricsId()`).
=> Adds id to server and updated serverId to metricsId

src/server_manager/model/server.ts, src/server_manager/web_app/app.spec.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/shadowbox_server.ts
This PR fixes a violations of domain-driven design: a concept was shared with model and serialization.
With the change the serialization format `DataUsageByAccessKey` is no longer shared with the model. Note how the old "UserId" concept is no longer exposed to the model.
I've renamed the serialization format `DataUsageByAccessKeyJson` and made it private, to make sure it doesn't leak.
I also renamed `ServerConfig` to `ServerConfigJson` to make it clearer that it's a serialization format.
/cc @alalamav @JonathanDCohen
=> Fix DataUsageByAccessKey and ServerConfig

.github/workflows/test.yml, .travis.yml, src/shadowbox/integration_test/target/Dockerfile, src/shadowbox/integration_test/test.sh
* Doesn't also build the Linux or Mac manager on server deploy
* Correctly builds a Windows binary on manager release (although we still have to manually upload build artifacts)
* Renames the Shadowbox deployment step
* Moves our unit tests to Github Actions to avoid the waiting on travis-ci.org
=> CI Updates

src/shadowbox/package.json, src/shadowbox/server/manager_service.ts, yarn.lock
To match newly cut version https://github.com/Jigsaw-Code/outline-shadowsocksconfig/releases/tag/v0.1.2
We never actually upgraded outlline-server to use the previous release, v.0.1.0. (Although outline client has been upgraded for a while.) So this is pulling in several config changes and lib updates: https://github.com/Jigsaw-Code/outline-shadowsocksconfig/compare/v0.0.9...v0.1.2
This is to fix https://github.com/Jigsaw-Code/outline-server/issues/774
=> bump ssconfig version

src/sentry_webhook/deploy_action.sh
- The sentry webhook cloud function is running on a deprecated node 6 runtime, causing all requests to fail.
- Updates the runtime to node 12.
=> Update sentry webhook runtime to node 12

third_party/shellcheck/run.sh
The shellcheck download verification step was relying on `sha256sum`,
which is not present in the macOS default install.
=> Fix shellcheck installation on macOS

src/server_manager/web_app/app.ts
Outline Manager `outline-do-oauth-step` unresponsive when the DigitalOcean login flow fails. 
This seems to happen when the DigitalOcean ` GET /v2/account` call returns `status !== active`, although it's difficult to reproduce.
This fixes the `loadDigitalOceanServers` return type and adds logic to disconnect and show intro when the DigitalOcean OAuth cancel button is pressed in app.
Fixes #816
=> Fixes unresponsive outline-do-oauth-step

src/server_manager/electron_app/release_linux_action.sh, src/server_manager/electron_app/release_macos_action.sh, src/server_manager/electron_app/release_windows_action.sh
Prevents us from creating signed 'development' releases.
=> Force production build environment for releases

src/server_manager/web_app/app.spec.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/ui_components/app-root.js, src/server_manager/web_app/ui_components/outline-server-list.ts, src/server_manager/web_app/ui_components/outline-server-view.js
This should fix the server removal issue.
The problem is that `dom-repeat` always removes the last node from the DOM tree, regardless of what entry was removed from the serverList. This has always happened, but the old code would always set all the view fields upon selection, mitigating the problem. I didn't capture the bug when testing because removing the last added server always works fine. You will only see the problem when you add two servers and delete the one before the last.
The old behavior had issues though, like flashing old content before showing new, and corner cases.
The new code uses the [lit-html repeat directive](https://lit-html.polymer-project.org/guide/writing-templates#repeating-templates), which properly maps the list items to dom nodes, deleting the right node when …
=> Fix server removal

src/server_manager/model/digitalocean.ts, src/server_manager/model/server.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/cloud_accounts.ts, src/server_manager/web_app/digitalocean_account.ts, src/server_manager/web_app/digitalocean_server.ts, src/server_manager/web_app/manual_server.ts, src/server_manager/web_app/testing/models.ts, src/server_manager/web_app/ui_components/app-root.js
This PR switches from using isManaged to using account ids.
This should help with the follow up to https://github.com/Jigsaw-Code/outline-server/pull/848, since you will need to ensure unique server ids.
Things to note:
- Ids are passed in the Server and Account constructors. This way we can ensure unique ids without server having to know about its Account, and Account knowing its Cloud.
- Account ID is just 'do' for now. We can use 'gcp', and in the future we can easily extend to actually include an account id (e.g. 'do:xyz1234')
- Manual servers have account id === null
This approach may simplify your GCP UI PR by allowing the accounts to be handled the same way.
For example, we could fire a "AccountSignOutRequested' with an accountId, which can pull the account and call …
=> Use Account ids

src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts
Fixes a bug where we don't load the data limits on individual keys from the config file when restarting the server.  This would result in dropping the data limits, while instead we want them to be properly persisted.
=> Load per key data limits from the config file

src/shadowbox/package.json
This is to release the bugfix from https://github.com/Jigsaw-Code/outline-server/pull/881
=> Bump shadowbox to 1.6.1

src/server_manager/model/server.ts, src/server_manager/web_app/app.ts
This fixes issues forgetting an unreachable server which were caused by the missing id keeping us from finding the server to forget.
Fix https://github.com/Jigsaw-Code/outline-server/issues/888
Fix https://github.com/Jigsaw-Code/outline-server/issues/886
Fix https://github.com/Jigsaw-Code/outline-server/issues/873
=> Populate an unreachable server's view with the server id

src/shadowbox/integration_test/run_action.sh
This should help occasional flaky failures we get from "permission failed" errors when trying to delete the log file
=> Force remove integration test logfiles

src/server_manager/web_app/ui_components/outline-gcp-create-server-app.ts
When billing accounts are present with long names, they would be cut off
on the left side.  This shifts the list to extend right instead of left.
=> Fix GCP billing account list visibility problem

src/server_manager/web_app/ui_components/outline-gcp-create-server-app.ts
This change disables the "create server" button in GCP when server
creation is in progress.
=> Prevent duplicate server creation in GCP

src/server_manager/model/gcp.ts, src/server_manager/web_app/gcp_account.ts, src/server_manager/web_app/testing/models.ts, src/server_manager/web_app/ui_components/outline-gcp-create-server-app.ts
This will also ensure that the user is prompted to add a billing account
if all the existing accounts are closed.
=> Hide closed billing accounts from the UI

src/server_manager/web_app/ui_components/app-root.js, src/server_manager/web_app/ui_components/outline-gcp-create-server-app.ts
This stops unnecessary polling if the user navigates away from the GCP flow
after logging in but before adding a billing account.
=> Stop refreshing billing status if the page is closed

.github/workflows/test.yml, src/server_manager/package.json
electron-builder cannot tolerate electron versions that are specified
with semantic versioning syntax: https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-547115107
This change also adds release builds to the presubmit, to prevent
regressions.
=> Fix electron-builder release builds

src/server_manager/cloud/gcp_api.ts, src/server_manager/web_app/gcp_account.ts, src/server_manager/web_app/gcp_server.ts
This provides a safer and clearer way to specify or read the scope of a
GCP operation.
=> Introduce types for GCP scopes

src/server_manager/cloud/gcp_api.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/gcp_account.ts, src/server_manager/web_app/gcp_server.ts
Currently, if the user starts server creation in GCP, they are stuck
on the region picker page until server creation completes. This takes
a long time, and is different from DigitalOcean, where server creation
is faster because it hasn't fully completed when the creation request
returns.
This change makes the GCP behavior match the DigitalOcean behavior, by
creating a ManagedServer object as soon as we know what the instance's
ID will be. This works by creating the Server object earlier, before
the instance is actually ready.
=> GCP: Make server creation more responsive

src/server_manager/install_scripts/gcp_install_server.sh, src/server_manager/web_app/gcp_account.ts, src/server_manager/web_app/gcp_server.ts
This cuts the GCP server setup time approximately in half, likely
because it avoids multiple calls to "apt update", which
synchronizes all known package repositories.
This PR also updates the underlying Ubuntu image to the latest LTS
release.
=> Install Docker on GCP using the Ubuntu dpkg method

src/server_manager/web_app/gcp_account.ts
e2-micro is the new GCP Free Tier instance type.  It's also faster and
has more RAM than the old f1-micro type.
=> Switch instance type to e2-micro

src/server_manager/web_app/gcp_account.ts
The current code generates names by concatenating integers in a custom
format, with several bugs:
* Leading zeros are discarded
* The date is in local time, but the time is in UTC.
* Months are presented zero-indexed (i.e. January is month zero)
This change corrects these issues.
=> Improve GCP instance name construction

src/server_manager/web_app/app.ts, src/server_manager/web_app/ui_components/outline-gcp-create-server-app.ts
When the free trial period expires, the Outline project is left linked
to an inactive billing account, and all instances are deleted.
Attempting to list the instances associated with a project that lacks
billing results in an HTTP 403.  Currently, this results in GCP login
failure, with a generic error message.
This change makes the manager handle this account state gracefully,
taking the user to the billing setup screen, and from there directly
to the server creation screen.
=> Fix login bug after free trial period expires

src/server_manager/electron_app/start.action.sh, src/server_manager/install_scripts/build_do_install_script_ts.node.js, src/server_manager/install_scripts/build_gcp_install_script_ts.node.js
`new Buffer` was deprecated in Node 8 (i believe) for security reasons. `readFileSync` already returns a `Buffer` - is there a reason we were doing this?
https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/
TODO:
=> Remove deprecated buffer constructor

src/server_manager/install_scripts/install_server.sh
Due to `umask 0007` set in `install_shadowbox` function, official docker installation script creates
`/usr/share/keyrings/docker-archive-keyring.gpg` file without read-other permission, which later
leads to permanent apt-update failure.
```
> Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl https://get.docker.com/ | sh'. [Y/n] y
> Installing Docker ........................... OK
> Verifying Docker installation ............... 
Last error: # Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sh -c apt-get update -qq >/dev/null
W: GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: …
```
=> Fix docker keyring permissions due to custom umask

src/shadowbox/server/manager_service.spec.ts
`bindService()` is a function exported by `manager_service` to bind the
service onto a Restify server.  This adds unit tests for this function.
=> Add unit tests for `bindService()`

package-lock.json, src/server_manager/electron_app/index.ts, src/server_manager/electron_app/tsconfig.json, src/server_manager/package.json, src/server_manager/web_app/data_formatting.spec.ts, src/server_manager/web_app/data_formatting.ts
This includes changes to the tsconfig recommended for Node.JS 16
and a required change to remove an obsolete attribute.
=> chore: Update electron to 18.1.0

src/server_manager/web_app/ui_components/outline-share-dialog.ts
https://github.com/Jigsaw-Code/outline-client/issues/1329
=> fix: broken link to invitation docs

src/server_manager/README.md, src/server_manager/electron_app/index.ts
Our app's icon is not shown in Ubuntu Dock because of the wrong image path:
After the fix, the icon is shown correctly on all platforms:
Related PR: https://github.com/Jigsaw-Code/outline-client/pull/1327
=> fix(manager): 💊 manager's icon is not shown in Ubuntu Dock

src/server_manager/electron_app/index.ts
https://git.radicallyopensecurity.com/ros/google-outline/-/issues/7
Seems to do the trick, don't see the dev tools here on mac anyway:
=> fix(manager): remove dev tools

src/server_manager/electron_app/index.ts
There is an Electron IPC event 'open-image' that accepts any path,
including relative paths that would expose system filenames such as
/etc/passwd.  This change resolves all paths to be rooted at the base
directory for ...server_manager/web_app.
=> fix: avoid malicious path traversal in manager's open-image method

src/server_manager/scripts/get_electron_build_flags.mjs
In this PR, I switched `electron-updater`'s checking-update-url to Amazon S3, so [`outline-releases` GitHub repository](https://github.com/Jigsaw-Code/outline-releases/tree/master/manager) can be deprecated (but we still need to update the yaml files for backward compatibility).
=> refactor(manager): ♻️ change electron-updater's url to S3

.github/workflows/pull_request_checks.yml
when the case here is flipped, the check gets skipped: https://github.com/Jigsaw-Code/outline-server/runs/8024106621?check_suite_focus=true
=> fix(devtools): only run the size label on internal PRs

src/server_manager/electron_app/digitalocean_oauth.ts
Changes the behavior of the local server for receiving oauth callbacks
from Digital Ocean by not closing it on invalid requests.  This avoids
the problem where a malicious actor prematurely closes the
callback-handling server (a DoS of the authentication flow).
Also added a timeout to close the server after 30 seconds.
=> fix: don't close the oauth callback server on bad requests

src/server_manager/install_scripts/install_server.sh
Add icanhazip.com as an alternative. Both ipinfo and checkip are sometimes inaccessible from certain areas.
=> feat(server): include icanhazip as an alternative to ipinfo and checkip of domains.google.com

src/server_manager/model/digitalocean.ts
The Sydney flag and its city name was not displayed appropriately in DigitalOcean's region selection page. It was a simple fix by just adding it to the available regions. Also [`substr` function is deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr), I replaced it with the [standard `substring` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring).
**after fix**
=> fix(manager/web): 💊 show Sydney flag in DO region page

src/shadowbox/infrastructure/logging.ts
This is polluting the log output. I need to fix this asap.
=> fix(server): don't output all log messages

src/shadowbox/infrastructure/get_port.spec.ts, src/shadowbox/infrastructure/get_port.ts
I found this issue because my DO server entered an infinite loop when I created a key on port 53. This happaned  because there's a systemd resolver daemon running on port 53, but our code failed to detect the port conflict.
Without the change to get_port, the IPv6 test fails.
=> fix(server): fix isPortUsed for IPv6

src/server_manager/web_app/ui_components/licenses/README.md, src/server_manager/web_app/ui_components/licenses/licenses.txt
Our [`licenses.txt`](https://github.com/Jigsaw-Code/outline-server/blob/508a5a2af5e076716ce91cbb08217075fe675e98/src/server_manager/web_app/ui_components/licenses/licenses.txt) file for Outline Manager is not correct, it is just a simple duplication of the [`README.md`](https://github.com/Jigsaw-Code/outline-server/blob/508a5a2af5e076716ce91cbb08217075fe675e98/src/server_manager/README.md). In this PR, I re-generate the `licenses.txt` file with all dependencies and update the steps in order to correctly generate it.
=> chore(manager): 📄 re-generate dependency licenses

package-lock.json, src/server_manager/base.webpack.js, src/server_manager/electron_app/build.action.sh, src/server_manager/electron_app/index.ts, src/server_manager/electron_app/preload.ts, src/server_manager/electron_main.webpack.mjs, src/server_manager/electron_preload.webpack.mjs, src/server_manager/package.json, src/server_manager/types/preload.d.ts, src/server_manager/web_app/app.ts, src/server_manager/web_app/ui_components/app-root.ts, src/server_manager/web_app/ui_components/outline-feedback-dialog.ts
In this PR, I integrated Outline Manager with the latest Sentry library and re-enabled the user feedback form. Sentry was not working because of two reasons:
1. Electron enabled sandbox to its `preload.js` script, therefore calling `Sentry.init` in `preload` is not enough (and not necessary), we must call `Sentry.init` in every renderer process as well
2. `SENTRY_DSN` is not injected into electron, we read it from `process.env.SENTRY_DSN`, but this is a runtime environment variable (which will be `undefined`)
So basically my fix is straightforward:
1. Calling `Sentry.init` in `web_app/app.ts`, which is the entrypoint of renderer process
2. Use `webpack` to inject `SENTRY_DSN_` variable into `electron_app/index.ts` during build
In order to be consistent (and to minify the result js file), …
=> fix(manager): 💊 integrate with the latest Sentry library

src/server_manager/install_scripts/install_server.sh
This PR aims to enhance the `docker_container_exists` function in `install_server.sh`. The previous implementation had issues with false negatives, making it unreliable in recognizing containers that were not currently running. In some cases, it even failed to recognize running containers. (I encountered this issue when using the script as a basis for a script that restarts Outline server containers.)
=> fix: improve Docker container existence detection in install_server.sh

src/shadowbox/docker/cmd.sh
This is unnecessarily restricting the server, which limits the number of connections we can support. This affected one of our partners. The call also can't raise the ulimit, since the host impose a cap on the container.
Those measurements were done when we uses ss-server, which we haven't used for several years.
Service providers can still set the ulimit on their host if they want to.
=> feat(server): remove ulimit

src/server_manager/electron_app/index.ts, src/server_manager/model/server.ts, src/server_manager/web_app/management_urls.ts, src/server_manager/web_app/manual_server.ts, src/server_manager/web_app/ui_components/app-root.ts
This makes it easier to add servers when they have a valid domain, working on the browser.
=> feat(manager): enable servers with valid domains

src/sentry_webhook/deploy.action.sh
Node.js 12 will be deprecated on Jan 30, 2024. This changes the runtime to Node.js 18, which is listed as the recommended version at https://cloud.google.com/functions/docs/concepts/nodejs-runtime.
=> chore(sentry_webhook): use Node.js 18 runtime version

package.json, src/server_manager/electron_and_karma_chromium.spec.ts, src/server_manager/package.json
This service is turned down. See https://groups.google.com/a/chromium.org/g/chromium-dev/c/uH-nFrOLWtE.
It's currently returning:
*** Service Permanently Offline ***
OmahaProxy has been turned down.
Please migrate to <https://chromiumdash.appspot.com>.
ChromiumDash is meant to replace this functionality.
=> fix(manager/electron): replace turned down OmahaProxy with ChromiumDash

src/server_manager/web_app/ui_components/app-root.ts
=> chore(manager/web): clean up unused `_computeSideBarMarginClass`

src/server_manager/install_scripts/do_install_server.sh, src/server_manager/install_scripts/install_server.sh
This PR makes the Manager use `--log-driver local` in the docker run, which is a log driver that does log rotation, unlike the default driver that keeps growing on disk and can make the server stop working after some time ([details](https://docs.docker.com/config/containers/logging/configure)). This is important, because some people may think the server gets blocked after some time.
This PR also creates a run script. That will help providers understand how to run the Outline server with Docker, and allow them to tweak how it is run. They can more easily change the API port, for instance. It's also a lot easier to change a server to the canary image. This is what is output on a standard installation:
```bash
#
set -eu
docker stop "shadowbox" 2> /dev/null || true
docker rm -f "shadowbox" 2> …
```
=> feat(server): enable log rotation and start script

src/server_manager/web_app/ui_components/outline-server-settings.ts
Fix [CWE-570](https://cwe.mitre.org/data/definitions/570.html) and [CWE-571](https://cwe.mitre.org/data/definitions/571.html)
More info: https://github.com/murka/outline-server/security/code-scanning/3
=> fix(manager): use typeof function instead of directly comparison

src/server_manager/install_scripts/install_server.sh
Small cleanup: use the config instead of the `SB_DEFAULT_SERVER_NAME` env var to specify the server name. Having two mechanisms is confusing, and this further simplifies the docker run command.
=> chore(manager): deprecate SB_DEFAULT_SERVER_NAME on install

src/shadowbox/model/access_key.ts, src/shadowbox/model/errors.ts, src/shadowbox/server/api.yml, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/server_access_key.spec.ts, src/shadowbox/server/server_access_key.ts
This was documented as part of #1273 and #1473 but not actually implemented. See https://github.com/Jigsaw-Code/outline-server/pull/1273#discussion_r1478851542.
=> feat(server): extend key creation API to allow specifying a port

src/shadowbox/server/api.yml
=> fix(server): api specification

src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts, src/sentry_webhook/post_sentry_event_to_salesforce.ts
Tested successfully with the dev webhook with both the old and new in-app contact form. The resulting cases look identical to the new webform created ones as they now use the same fields.
There is one outstanding UAT record ID, which I've requested and will update before merging.
=> feat(sentry_webhook): update Salesforce record IDs for new contact form

src/shadowbox/README.md, src/shadowbox/model/shadowsocks_server.ts, src/shadowbox/scripts/update_mmdb.sh, src/shadowbox/server/api.yml, src/shadowbox/server/main.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/mocks/mocks.ts, src/shadowbox/server/outline_shadowsocks_server.ts, src/shadowbox/server/server_config.ts, third_party/outline-ss-server/Makefile
Will wait on a new non-beta release of `outline-ss-server` once https://github.com/Jigsaw-Code/outline-ss-server/pull/171 is merged, but thought I'd get the PR review started.
The IP-to-ASN database is provided to `outline-ss-server` at server startup instead of via the server config, so here we SIGTERM the process for restart when the ASN metric is enabled. Since this is only ever meant to be an experimental API, that is probably ok. We can always move it to the server config if we want to graduate the endpoint to be a stable API.
=> feat(server): add an experimental opt-in API to enable ASN metrics

src/shadowbox/server/api.yml
Semantic error at paths./access-keys/{id}
Declared path parameter "id" needs to be defined within every operation in the path (missing in "put")
fix error from swagger editor and another open api viewers
=> chore: update api.yml

src/metrics_server/README.md
When we [moved from Cloud Functions to GAE](https://github.com/Jigsaw-Code/outline-server/pull/577/files#diff-99b64d57d0ef44ed1c2d821cd7dc7129d3ccf7a727113973f045739f238c910a) the deployment was configured with [`--no-promote`](http://cloud/sdk/gcloud/reference/app/deploy#--promote), but the instructions were never updated.
=> docs(metrics_server): add note about promoting the prod version

src/shadowbox/model/access_key.ts, src/shadowbox/server/main.ts, src/shadowbox/server/server_access_key.ts, src/shadowbox/server/shared_metrics.spec.ts, src/shadowbox/server/shared_metrics.ts
We no longer use the access key metrics ID, as we stopped sending it in https://github.com/Jigsaw-Code/outline-server/pull/1529.
=> refactor(server): remove unneeded access key metrics ID

.github/workflows/build_and_test_debug.yml, src/shadowbox/integration_test/client/Dockerfile
Alpine 3.19 curl is using the c-ares resolver instead of the system resolver. This is causing [DNS issues in the integration test](https://github.com/Jigsaw-Code/outline-server/actions/runs/9993257424/job/27620375345):
```
curl: (6) Could not resolve host: shadowbox
```
See https://github.com/curl/curl/issues/12558 and https://github.com/c-ares/c-ares/issues/683 for details.
=> test(server): fix integration test by downgrading to Alpine 3.18

src/shadowbox/model/shadowsocks_server.ts, src/shadowbox/server/api.yml, src/shadowbox/server/main.ts, src/shadowbox/server/manager_service.spec.ts, src/shadowbox/server/manager_service.ts, src/shadowbox/server/mocks/mocks.ts, src/shadowbox/server/outline_shadowsocks_server.ts, src/shadowbox/server/server_config.ts
I left a reference behind in `server_config.ts` so we can identify existing values in server configs. Everything else has been removed.
=> feat: roll out ASN metrics to all servers

go.mod, go.sum, package-lock.json, package.json
We are also missing the webpack CLI dependency, which the task automatically adds on a docker run. Sweeping that into this PR.
=> chore: update `outline-ss-server` dependency to latest version

src/sentry_webhook/README.md, src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts, src/sentry_webhook/post_sentry_event_to_salesforce.ts
This is a new tag that will be set by the user on the Contact Us form in the Client and Manager apps in the near future, to mirror the new option in the https://support.getoutline.org form. It allows users to opt-in to being contacted in the future.
=> feat(sentry_webhook): handle `outreachConsent` Sentry tag

src/shadowbox/server/manager_metrics.spec.ts, src/shadowbox/server/manager_metrics.ts
Also slightly changed the shape to avoid confusion between data transferred (total) and bandwidth (rate per second).
=> feat(server): use `rate()` over `increase()` for bandwidth calculations

src/shadowbox/server/api.yml, src/shadowbox/server/manager_metrics.spec.ts, src/shadowbox/server/manager_metrics.ts
We decided not to show "last connected" in the UI, so I'm removing it for now on the endpoint so we don't continue to unnecessarily support this datapoint.
=> chore: remove lastConnected property and update OpenAPI spec

.github/workflows/build_and_test_debug.yml
This fixes the Sentry webhook CI job. See https://github.com/puppeteer/puppeteer/issues/12818 for details on the error.
=> ci(sentry_webhook): pin Ubuntu due to Chromium bug (via Puppeteer)

src/shadowbox/server/main.ts
This will unblock upgrading to Prometheus v3.
"Prometheus v3 is more strict concerning the `Content-Type` header received when scraping. Prometheus v2 would default to the standard Prometheus text protocol if the target being scraped did not specify a Content-Type header or if the header was unparsable or unrecognised. This could lead to incorrect data being parsed in the scrape. Prometheus v3 will now fail the scrape in such cases." See https://prometheus.io/docs/prometheus/latest/migration/#scrape-protocols.
=> chore(server): set `Content-Type` header on Prom metrics endpoint
